// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: alert.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 告警类型
type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED AlertType = 0
	AlertType_SERVICE_ALERT          AlertType = 1 // 内部服务告警
	AlertType_DRIVER_ALERT           AlertType = 2 // 驱动告警
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "SERVICE_ALERT",
		2: "DRIVER_ALERT",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED": 0,
		"SERVICE_ALERT":          1,
		"DRIVER_ALERT":           2,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_alert_proto_enumTypes[0].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_alert_proto_enumTypes[0]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

// 告警级别
type AlertLevel int32

const (
	AlertLevel_ALERT_LEVEL_UNSPECIFIED AlertLevel = 0
	AlertLevel_ERROR_LEVEL             AlertLevel = 1 // error
	AlertLevel_WARN_LEVEL              AlertLevel = 2 // warn
	AlertLevel_NOTIFY_LEVEL            AlertLevel = 3 // notify
)

// Enum value maps for AlertLevel.
var (
	AlertLevel_name = map[int32]string{
		0: "ALERT_LEVEL_UNSPECIFIED",
		1: "ERROR_LEVEL",
		2: "WARN_LEVEL",
		3: "NOTIFY_LEVEL",
	}
	AlertLevel_value = map[string]int32{
		"ALERT_LEVEL_UNSPECIFIED": 0,
		"ERROR_LEVEL":             1,
		"WARN_LEVEL":              2,
		"NOTIFY_LEVEL":            3,
	}
)

func (x AlertLevel) Enum() *AlertLevel {
	p := new(AlertLevel)
	*p = x
	return p
}

func (x AlertLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_alert_proto_enumTypes[1].Descriptor()
}

func (AlertLevel) Type() protoreflect.EnumType {
	return &file_alert_proto_enumTypes[1]
}

func (x AlertLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertLevel.Descriptor instead.
func (AlertLevel) EnumDescriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{1}
}

type AlertReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version     string     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ServiceName string     `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	AlertType   AlertType  `protobuf:"varint,4,opt,name=alert_type,json=alertType,proto3,enum=alert.AlertType" json:"alert_type,omitempty"`
	AlertLevel  AlertLevel `protobuf:"varint,5,opt,name=alert_level,json=alertLevel,proto3,enum=alert.AlertLevel" json:"alert_level,omitempty"`
	T           int64      `protobuf:"varint,6,opt,name=t,proto3" json:"t,omitempty"`
	Content     string     `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AlertReportReq) Reset() {
	*x = AlertReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertReportReq) ProtoMessage() {}

func (x *AlertReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertReportReq.ProtoReflect.Descriptor instead.
func (*AlertReportReq) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AlertReportReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertReportReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AlertReportReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AlertReportReq) GetAlertType() AlertType {
	if x != nil {
		return x.AlertType
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *AlertReportReq) GetAlertLevel() AlertLevel {
	if x != nil {
		return x.AlertLevel
	}
	return AlertLevel_ALERT_LEVEL_UNSPECIFIED
}

func (x *AlertReportReq) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *AlertReportReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AlertReportResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AlertReportResp) Reset() {
	*x = AlertReportResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertReportResp) ProtoMessage() {}

func (x *AlertReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertReportResp.ProtoReflect.Descriptor instead.
func (*AlertReportResp) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AlertReportResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertReportResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AlertReportResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_alert_proto protoreflect.FileDescriptor

var file_alert_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x22, 0xea, 0x01, 0x0a, 0x0e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x0a, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x5c, 0x0a, 0x0f, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0x4c, 0x0a, 0x09, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16,
	0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x52, 0x56,
	0x49, 0x43, 0x45, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44,
	0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x10, 0x02, 0x2a, 0x5c, 0x0a,
	0x0a, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x17, 0x41,
	0x4c, 0x45, 0x52, 0x54, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x41, 0x52,
	0x4e, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54,
	0x49, 0x46, 0x59, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x10, 0x03, 0x32, 0x52, 0x0a, 0x12, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x15, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_alert_proto_rawDescOnce sync.Once
	file_alert_proto_rawDescData = file_alert_proto_rawDesc
)

func file_alert_proto_rawDescGZIP() []byte {
	file_alert_proto_rawDescOnce.Do(func() {
		file_alert_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_proto_rawDescData)
	})
	return file_alert_proto_rawDescData
}

var file_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alert_proto_goTypes = []interface{}{
	(AlertType)(0),          // 0: alert.AlertType
	(AlertLevel)(0),         // 1: alert.AlertLevel
	(*AlertReportReq)(nil),  // 2: alert.AlertReportReq
	(*AlertReportResp)(nil), // 3: alert.AlertReportResp
}
var file_alert_proto_depIdxs = []int32{
	0, // 0: alert.AlertReportReq.alert_type:type_name -> alert.AlertType
	1, // 1: alert.AlertReportReq.alert_level:type_name -> alert.AlertLevel
	2, // 2: alert.AlertReportService.AlertReport:input_type -> alert.AlertReportReq
	3, // 3: alert.AlertReportService.AlertReport:output_type -> alert.AlertReportResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_proto_init() }
func file_alert_proto_init() {
	if File_alert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertReportResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_proto_goTypes,
		DependencyIndexes: file_alert_proto_depIdxs,
		EnumInfos:         file_alert_proto_enumTypes,
		MessageInfos:      file_alert_proto_msgTypes,
	}.Build()
	File_alert_proto = out.File
	file_alert_proto_rawDesc = nil
	file_alert_proto_goTypes = nil
	file_alert_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AlertReportServiceClient is the client API for AlertReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlertReportServiceClient interface {
	AlertReport(ctx context.Context, in *AlertReportReq, opts ...grpc.CallOption) (*AlertReportResp, error)
}

type alertReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertReportServiceClient(cc grpc.ClientConnInterface) AlertReportServiceClient {
	return &alertReportServiceClient{cc}
}

func (c *alertReportServiceClient) AlertReport(ctx context.Context, in *AlertReportReq, opts ...grpc.CallOption) (*AlertReportResp, error) {
	out := new(AlertReportResp)
	err := c.cc.Invoke(ctx, "/alert.AlertReportService/AlertReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertReportServiceServer is the server API for AlertReportService service.
type AlertReportServiceServer interface {
	AlertReport(context.Context, *AlertReportReq) (*AlertReportResp, error)
}

// UnimplementedAlertReportServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlertReportServiceServer struct {
}

func (*UnimplementedAlertReportServiceServer) AlertReport(context.Context, *AlertReportReq) (*AlertReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlertReport not implemented")
}

func RegisterAlertReportServiceServer(s *grpc.Server, srv AlertReportServiceServer) {
	s.RegisterService(&_AlertReportService_serviceDesc, srv)
}

func _AlertReportService_AlertReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertReportServiceServer).AlertReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alert.AlertReportService/AlertReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertReportServiceServer).AlertReport(ctx, req.(*AlertReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlertReportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alert.AlertReportService",
	HandlerType: (*AlertReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AlertReport",
			Handler:    _AlertReportService_AlertReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alert.proto",
}
